### ISSUE TITLE
Velocity Vector does NOT Specify Units

### ISSUE THREAD

**Issue by tydlwav** [tydlwav/GSW-Sat-Tracking#1]
We would need another way of calculating speed as the velocity vector documentation does not offer the unit it uses so we would not be able to convert it to human-readable speeds. We would need another implementation.

**Comment by kdu4108** [comment]
No it's km/s in x y z, if you take the magnitude you get the speed shown by the official ISS tracker

**Comment by tydlwav** [comment]
OK, fixed code.
